### PR TITLE
added homework

### PR DESCRIPTION
**Pull request by nikhitakamath**

### CODE REVIEW

**Comment by eddiewash** [comment]
@nikhitakamath hey! it looks like you've changed a few of the class files that are not in your folder. would you be able to change those files back the way they were on your laptop and then push to your repo again? if you need some help, let me know!

After you do that I can merge your request :+1:

**Comment by nikhitakamath** [comment]
For sure! Can you give me some more assistance on how to do it? 

- Nikhita Kamath

**Comment by trivett** [comment]
Hey @nikhitakamath. Just go into your class folder and use the mv command. for example: 

$ ` mv classwork/class2/rubymadlib1 nikhita_kamath/class2/`

**Comment by trivett** [comment]
LGTM!

**Pull request merged**
