### PR TITLE
HW and fixing file conflicts

### PR DESCRIPTION
**Pull request by peterlin741**
HW1

### CODE REVIEW

**Comment by eddiewash** [comment]
@peterlin741 hey man! It looks like you've changed a few of the class files that are outside of your folder. I can't merge your pull request yet because it will give us merge conflicts. Try moving all of the files your changed into your folder and then git add/commit/push again and that will automatically update your pull request.

Happy to help you out if it gives you any trouble.

**Comment by trivett** [comment]
@peterlin741 Looks like you are changing file mode on everything and duplicating a bunch of stuff. Before we merge this in, let's try to solve this together.

**Comment by peterlin741** [comment]
Yeah I Had some trouble with it, I'll try to fix it again tonight

**Comment by peterlin741** [comment]
There were 3 hidden ".DS_Store" files that were removed, but I fixed the other conflicts

**Comment by trivett** [comment]
phew! Thanks for fixing that up.

**Pull request merged**
